os:
    - linux
dist: trusty
sudo: false
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget -q https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then wget -q https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
- export PATH="$HOME/miniconda/bin:$PATH"
- bash miniconda.sh -b -p $HOME/miniconda
- conda config --set always_yes yes --set changeps1 no
- conda update -y -q conda
script:
- export UVCDAT_ANONYMOUS_LOG=False
- export UVCDAT_SETUP_PATH=${HOME}
- conda create -q -n py2 -c cdat/label/nightly -c nesii/label/dev-esmf -c conda-forge -c uvcdat cdms2 cdat_info udunits2 nose flake8 genutil matplotlib vtk-cdat image-compare cdutil vcs "proj4<5" "python<3"
- conda install -q -n py2 -c cdat/label/nightly -c conda-forge mesalib
- conda create -q -n py3 -c cdat/label/nightly -c nesii/label/dev-esmf -c conda-forge -c uvcdat cdms2 cdat_info udunits2 nose flake8 genutil matplotlib vtk-cdat image-compare cdutil vcs "proj4<5" "python>3"
- conda install -q -n py3 -c cdat/label/nightly -c conda-forge mesalib
- echo $TRAVIS_BRANCH
- export TRAVIS_PR_BRANCH=$TRAVIS_BRANCH
- echo $TRAVIS_EVENT_TYPE
- echo $TRAVIS_PULL_REQUEST
- source activate py2
- python setup.py install
- git clone git://github.com/uv-cdat/uvcdat-testdata
- cd uvcdat-testdata ; git checkout $TRAVIS_BRANCH ; cd ..
- df -h
- python run_tests.py -v2 -n2 -g
- source activate py3
- rm -rf build
- python setup.py install
- python run_tests.py -v2 -n2 -g
after_success:
    - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then conda install -n root conda-build anaconda-client && bash ci-support/conda_upload.sh ; fi
